(defun fact (n) (if (< n 2) 1 (* n (fact (- n 1)))))
(print (fact 20))
(print (* 4000000000 4))
(print (address-of 'car))
(print (list 1 2.5 "str" #\a 'sym))
(setq l nil)
(dotimes (i 20000) (setq l (cons i l)))
(print (length l))
(gc)
(print (apply #'+ (list 1 2 3 4)))
(print (mapcar #'(lambda (x) (* x x)) '(1 2 3 4 5)))
(print (sort '(5 3 9 1 7) #'<))
(print (catch 'foo (throw 'foo 42)))
(print (errset (car 5) nil))
(print (unwind-protect (+ 1 2) (print 'cleanup)))
(setq s (make-string-output-stream))
(dotimes (i 50) (princ i s))
(dotimes (i 3000) (list i i i))
(gc)
(print (get-output-stream-string s))
(print (string-upcase "hello world"))
(print (strcat "abc" "def"))
(print (subseq "hello world" 6))
(print (format nil "~a and ~s" "x" "y"))
(print (read (make-string-input-stream "(a b (c d) 123 4.5)")))
(setq v (make-array 10))
(setf (aref v 3) 'three)
(print v)
(print (assoc 'b '((a 1) (b 2))))
(print (float 7))
(print (truncate 7.9))
(print (sqrt 2.0))
(print (/ 7 2))
(print (rem -7 2))
(print (logand 255 15))
(print (expt 2.0 10.0))
(print (< 1 2 3))
(print (= 5 5.0))
(print (> -9223372036854775807 9223372036854775807))
(print #x7fffffffffffffff)
(defmacro my-inc (v) `(setq ,v (+ ,v 1)))
(setq z 5) (my-inc z) (print z)
(setq my-class (send class :new '(a b)))
(send my-class :answer :isnew '(x) '((setq a x) self))
(send my-class :answer :geta '() '(a))
(setq obj (send my-class :new 99))
(print (send obj :geta))
(print (type-of obj))
(pprint '(defun foo (a b) (let ((c (+ a b))) (if (> c 10) (print c) (print (- c))))))
(print (symbol-name 'abc))
(print (gensym))
(print (let* ((x 1) (y (+ x 1))) (list x y)))
(print (do ((i 0 (1+ i)) (acc nil (cons i acc))) ((= i 5) acc)))
(print (block b (return-from b 'early) 'late))
(print (random 100))
(print (equal '(1 (2 3)) '(1 (2 3))))
(print (reverse '(1 2 3)))
(print (nth 2 '(a b c d)))
(print (member 'c '(a b c d)))
(print (remove-if #'evenp '(1 2 3 4 5 6)))
(print (char-code #\A))
(print (string< "abc" "abd"))
(print (flatsize '(a b c)))

(room)
(exit)
