(defun show (x) (print x))
(show (string-upcase (strcat "abc" "def" "ghi")))
(show (string-trim " " "  padded  "))
(show (string-left-trim "x" "xxabc"))
(show (subseq "hello world" 0 5))
(show (char "abc" 1))
(show (string< "apple" "banana"))
(show (string-equal "ABC" "abc"))
(show (nstring-downcase (strcat "MiXeD" "")))
(show (char-upcase #\a))
(show (digit-char-p #\7))
(show (code-char 65))
(show (int-char 66))
(setq ss (make-string-input-stream "line one
line two"))
(show (read-line ss))
(show (read-line ss))
(show (read-line ss))
(setq os (make-string-output-stream))
(dotimes (i 200) (prin1 (list i "s" #\c) os))
(show (length (get-output-stream-string os)))
(dotimes (i 50) (princ i os))
(show (get-output-stream-list os))
(show (format nil "~a/~s/~%~~" 'x "y"))
(defmacro swap (a b) `(let ((tmp ,a)) (setq ,a ,b) (setq ,b tmp)))
(setq p 1 q 2) (swap p q) (show (list p q))
(show (macroexpand '(swap p q)))
(defun kf (a &optional (b 2 bp) &rest r &key (k 9) &aux (z 7)) (list a b bp r k z))
(show (kf 1))
(show (kf 1 3 :k 4))
(setq pl nil)
(putprop 'foo 1 'bar) (putprop 'foo 2 'baz) (remprop 'foo 'bar)
(show (symbol-plist 'foo))
(setq v (vector 1 2 3)) (setf (aref v 1) 'two) (show v)
(setq l (list 1 2 3)) (setf (nth 1 l) 'x) (setf (car l) 'a) (show l)
(show (sort (list 5 1 4 2 3 9 8 7 6) #'<))
(show (mapcar #'+ '(1 2 3) '(10 20 30)))
(show (maplist #'length '(1 2 3)))
(show (subst 'z 'b '(a b (b c))))
(show (sublis '((a . 1) (b . 2)) '(a b c)))
(show (delete 3 (list 1 3 2 3)))
(show (remove-if-not #'numberp '(1 a 2 b)))
(show (assoc "b" '(("a" 1) ("b" 2)) :test #'equal))
(show (member 2.0 '(1 2 3) :test #'=))
(show (nconc (list 1 2) (list 3) nil (list 4)))
(show (append '(1) '(2) '(3 4)))
(show (catch 'x (unwind-protect (throw 'x 'thrown) (show 'unwinding))))
(show (block outer (dolist (i '(1 2 3)) (if (= i 2) (return-from outer i)))))
(show (prog ((i 0)) loop (setq i (1+ i)) (if (< i 5) (go loop)) (return i)))
(show (errset (error "custom" 42) t))
(show (errset (/ 1 0) nil))
(show (let ((x 1)) (flet ((f (y) (+ x y))) (f 10))))
(show (labels ((fact (n) (if (< n 2) 1 (* n (fact (1- n)))))) (fact 10)))
(show (funcall (let ((c 0)) #'(lambda () (setq c (1+ c)))) ))
(setq counter-class (send class :new '(count)))
(send counter-class :answer :isnew '() '((setq count 0) self))
(send counter-class :answer :inc '() '((setq count (1+ count))))
(setq sub-class (send class :new '(extra) '() counter-class))
(send sub-class :answer :inc '() '((send-super :inc) (send-super :inc)))
(setq c1 (send sub-class :new))
(send c1 :inc) (show (send c1 :inc))
(send c1 :show)
(show (progv '(dyn1 dyn2) '(10 20) (+ dyn1 dyn2)))
(show (case 3 (1 'one) ((2 3) 'two-or-three) (t 'other)))
(show (cond ((> 1 2) 'no) ((< 1 2) 'yes)))
(show (and 1 2 3)) (show (or nil nil 4))
(show (let* ((a 1) (b (* a 10))) (+ a b)))
(show (do* ((i 0 (1+ i)) (j i i)) ((= i 3) j)))
(show (eval '(+ 1 2)))
(show (apply #'max '(3 9 2)))
(show (equal (read (make-string-input-stream "#(1 2 (3))")) (vector 1 2 '(3))))
(show (symbol-name (intern "INTERNED")))
(show (fboundp 'car)) (show (boundp 'undefined-thing))
(show (get-lambda-expression #'show))
(trace show) (show 'traced) (untrace show)
(pprint '(let ((a 1) (b 2)) (cond ((> a b) (print "a bigger")) (t (print "b bigger")))))
(show (flatc "abc")) (show (flatsize "abc"))
(show (logxor 5 3)) (show (lognot 0)) (show (gcd 12 18)) (show (abs -5))
(show (sqrt 16.0)) (show (exp 0.0)) (show (sin 0.0))
(show (min 3 1 2)) (show (max 1.5 2))
(show (evenp 4)) (show (oddp 4)) (show (zerop 0.0)) (show (plusp -1)) (show (minusp -1))
(show (type-of 1.5)) (show (type-of #\a)) (show (type-of "s")) (show (type-of #'car)) (show (type-of 'quote))
(setq big nil)
(dotimes (i 3000) (setq big (cons (make-array 3) big)))
(show (length big))
(show (hash "abc" 199))
(show 'done)
